.TH "BRACELET GENERATOR" "1" "January 2017" "bracelet-generator 1.4.0" ""
.SH NAME
BraceletGenerator \- An easy way to design friendship bracelet patterns
.SH SYNOPSIS
.B bracelet-generator
.RI [file_name]
.SH DESCRIPTION
BraceletGenerator is a friendship bracelet pattern designer.
It enables you to easily design your own patterns, add rows and strings, change the colors.
With the two-colored motif editor, create your motif and the pattern will automatically be generated.
The patterns can be exported in .png, .jpe, .ps and in text format.
.SH OPTIONS
.TP
.B file_name
Optional. The name of the file (.bracelet or .bicolor) to open.
.SH AUTHOR
BraceletGenerator is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the SourceForge page of the project
\fBhttps://sourceforge.net/p/braceletgenerator/tickets/\fR 
or send an email to <j_4321@protonmail.com>.
